name: Docker CI - multi service

on:
  push:
    branches: [main, dev]

jobs:
  build-service-1:
    name: Build & Test Service 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image for service-1
        run: docker build -t DevOps/service-1:latest .

      - name: Run tests for service-1
        run: |
          npm install
          npm test

  build-service-2:
    name: Build & Test Service 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image for service-2
        run: docker build -t DevOps/service-2:latest ./service-2

      - name: Run tests for service-2
        run: |
          cd service-2
          npm install
          npm test
